# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2fc44d68c859d863955a9509958d5e9e6f9c76c463b1810c4c86abeb6c75ea9f00d2b947b713ceaf96af2daa24300814c44e123d50d1f893d123d4034f701a9

test:
  secret_key_base: 12199dbca3048fa5566459fc0d8c39c19100d5f3168d53ea7616bc576d77581231296109442ffb022113820b063e01e99271c90e8613d882561e6bed77f80bb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
